from fastapi import APIRouter
from app.api.v1 import (auth, projects, cases, environments, scripts, devices, apks,
                         device_mirror, suites, plans, webhook, exports, notifications,
                         statistics, mock_rules, bug_trackers, mobile_special, global_variables, storage, traces)

router = APIRouter(prefix="/api/v1")
router.include_router(auth.router)
router.include_router(projects.router)
router.include_router(cases.router)
router.include_router(environments.router)
router.include_router(scripts.router)
router.include_router(devices.router)
router.include_router(apks.router)
router.include_router(device_mirror.router)
router.include_router(suites.router)
router.include_router(plans.router)
router.include_router(webhook.router)
router.include_router(exports.router)
router.include_router(notifications.router)
router.include_router(statistics.router)
router.include_router(mock_rules.router)
router.include_router(bug_trackers.router)
router.include_router(mobile_special.router)
router.include_router(global_variables.router)
router.include_router(storage.router)
router.include_router(traces.router)
