from fastapi import APIRouter
from app.api.v1 import (auth, projects, cases, environments, scripts, devices, apks,
                         device_mirror, suites, plans, webhook, exports, notifications,
                         statistics, mock_rules, bug_trackers, mobile_special, global_variables, storage, traces,
                         ai_llm_configs, ai_case_generation, admin_runs, datasets, dashboard_alerts)

router = APIRouter(prefix="/api/v1")
router.include_router(auth.router)
router.include_router(projects.router)
router.include_router(cases.router)
router.include_router(environments.router)
router.include_router(scripts.router)
router.include_router(devices.router)
router.include_router(apks.router)
router.include_router(device_mirror.router)
router.include_router(suites.router)
router.include_router(plans.router)
router.include_router(webhook.router)
router.include_router(exports.router)
router.include_router(notifications.router)
router.include_router(statistics.router)
router.include_router(mock_rules.router)
router.include_router(bug_trackers.router)
router.include_router(mobile_special.router)
router.include_router(global_variables.router)
router.include_router(storage.router)
router.include_router(traces.router)
router.include_router(ai_llm_configs.router)
router.include_router(ai_case_generation.router)
router.include_router(admin_runs.router)
router.include_router(datasets.router)
router.include_router(dashboard_alerts.router)
