export const hermesActionsZh = {
  dispatch_pending: '待投递', dispatch_publishing: '投递中', dispatch_submitted: '已入队', dispatch_uncertain: '投递需核对', dispatch_blocked: '投递受阻', dispatch_skipped: '未继续投递',
  refresh_history: '刷新服务端状态', run_pending: '待执行／投递待核对', run_running: '运行中', run_passed: '运行通过', run_failed: '运行失败', run_error: '运行异常', run_cancelled: '已取消', run_missing: '原记录已删除或身份变化', run_unverified: '历史资源身份待核对',
  timeout_seconds: '步骤超时（秒）',
  request_number: '请求 {index}', method: '请求方法', url: '接口地址', remove: '删除', add_assertion: '添加断言', edit_steps: '编辑步骤与断言', invalid_api: '请填写用例名称、接口地址，并为每个请求保留有效断言。', history: '最近处理记录', history_scope: '合并服务端套件操作记录与当前会话记录，最多显示 20 条。运行状态需刷新；待执行可能需要核对投递，不会自动重试。', history_unavailable: '浏览器无法保存处理记录，请保留当前面板并查看结果。', status_pending: '正在提交', status_completed: '已提交成功', status_uncertain: '状态待核对',
  environment: '运行环境', no_environment: '不指定环境', diagnose: '分析所选失败运行', review_required: '保存后沿用原审核流程；助手不会自动批准用例或立即执行。',
  title: '帮你处理测试', record: '完善录制', api: '生成接口用例', regression: '组织回归', repair: '修复定位器', android: '运行安卓用例', defect: '整理缺陷', knowledge: '保存经验', summary: '测试总结',
  preview_hint: '先准备并查看具体内容；保存与执行需要确认。接口用例生成会使用当前项目绑定的模型。',
  case: '选择用例', module: '保存到模块', schema_type: '接口描述格式', schema: '粘贴接口描述（cURL / OpenAPI / Postman）', expected_text: '执行结束后应出现的文本', old_locator: '需要替换的原定位器', new_locator: '确认后的新定位器', cases: '用例', failure_run: '失败运行', name: '名称', requirement: '业务要求 / 补充说明', days: '最近天数', prepare: '准备建议', preview: '待确认内容', save_this: '保存这条用例', request_details: '查看请求与断言', confirm: '我已查看内容，确认保存或执行以上操作', apply: '确认处理', done: '处理完成', open_result: '查看结果', confirm_run: '确认运行刚创建的回归套件（可能产生业务数据）', run_suite: '执行回归套件', download: '下载 Markdown',
  partial_load: '部分项目数据读取失败，请重新打开面板；缺失的数据不会参与推荐。', failed: '操作失败，请查看具体错误', editor_required: '当前项目需要编辑权限', choose_case: '请选择当前项目的用例', no_recording: '该用例没有可整理的低代码步骤', invalid_steps: '录制步骤格式不完整，请在用例详情检查', locators_required: '请填写原定位器和确认后的新定位器', locator_not_found: '步骤中没有找到该原定位器', locators_changed: '将替换 {count} 个步骤的定位器', expected_required: '请说明应出现的结果文本，助手不会猜测业务断言', assertion: '验证预期文本', timeout_note: '使用现有低代码执行器；保留原步骤超时，缺失时默认 30 秒；可在预览中调整。元素操作自动等待。', schema_required: '请选择模块并粘贴接口描述', endpoint_limit: '请提供 1～20 个接口，超出时拆分后生成', no_drafts: '模型没有返回可用草稿', select_cases: '请填写名称并选择至少一条用例', not_ready: '选中用例尚不可执行，请先完善配置或审核状态', run_separate: '先创建串行套件；执行时另行确认。未自动选择运行环境。', device_not_ready: '用例不可执行，或绑定设备尚未在线／当前被占用', apk_missing: '绑定的 APK 不在当前项目', device_cached: '此处依据设备最近同步状态；实际 ADB 连接、应用安装及启动仍由执行器检查。', installed_app: '使用用例配置的已安装应用', choose_run: '请选择当前项目的失败用例运行', not_failure: '该运行当前不是失败或异常状态', evidence_link: '缺陷将关联原始运行；现有服务会检查重复缺陷。', content_required: '请填写知识标题和内容', knowledge_draft: '保存为当前项目的知识草稿，可在知识库继续编辑后发布。', summary_limit: '汇总当前项目用例运行与开放缺陷；明细最多 50 条，统计数据覆盖所选时间范围。', period: '统计范围：最近 {days} 天（滚动时间窗口）', summary_metrics: '运行 {runs} 次；通过 {passed}，失败 {failed}，异常 {error}；通过率 {rate}%；当前开放缺陷 {defects}。', stale: '用例在预览后发生变更，请重新准备建议', import_failed: '导入结果不完整，请到用例列表核对后再操作', duplicate_defect: '已有对应缺陷，已返回现有记录', check_before_retry: '请求可能已处理，请先查看记录，避免重复提交。', completed_message: '{action}已处理，请打开结果查看。', run_started: '回归运行 #{id} 已提交，可在套件运行记录查看状态。', regression_name: 'Hermes 回归套件', knowledge_name: '项目测试经验',
}
export const hermesActionsEn = {
  dispatch_pending: 'Awaiting dispatch', dispatch_publishing: 'Dispatching', dispatch_submitted: 'Queued', dispatch_uncertain: 'Verify dispatch result', dispatch_blocked: 'Dispatch blocked', dispatch_skipped: 'No further dispatch',
  refresh_history: 'Refresh server status', run_pending: 'Pending / check dispatch', run_running: 'Running', run_passed: 'Passed', run_failed: 'Failed', run_error: 'Error', run_cancelled: 'Cancelled', run_missing: 'Original record deleted or replaced', run_unverified: 'Verify legacy resource identity',
  timeout_seconds: 'Step timeout (seconds)',
  request_number: 'Request {index}', method: 'Method', url: 'Request URL', remove: 'Remove', add_assertion: 'Add assertion', edit_steps: 'Edit steps and assertions', invalid_api: 'Enter case names and request URLs, and keep valid assertions for every request.', history: 'Recent actions', history_scope: 'Combines server suite records with session records, up to 20 entries. Refresh run status; pending runs may need dispatch checks. Retries are never automatic.', history_unavailable: 'Browser action history is unavailable. Keep this panel open and check the result.', status_pending: 'Submitting', status_completed: 'Submitted successfully', status_uncertain: 'Check result',
  environment: 'Execution environment', no_environment: 'No environment', diagnose: 'Analyze selected failed run', review_required: 'Saved cases follow the existing review workflow; the assistant does not automatically approve or run them.',
  title: 'Testing assistance', record: 'Improve recording', api: 'Generate API cases', regression: 'Organize regression', repair: 'Repair locators', android: 'Run Android case', defect: 'Create defect', knowledge: 'Save experience', summary: 'Test summary',
  preview_hint: 'Review the proposed content before confirming a save or execution. API generation uses the project model.',
  case: 'Case', module: 'Target module', schema_type: 'API format', schema: 'API description (cURL / OpenAPI / Postman)', expected_text: 'Text expected at the end', old_locator: 'Original locator', new_locator: 'Verified replacement locator', cases: 'Cases', failure_run: 'Failed run', name: 'Name', requirement: 'Requirements / notes', days: 'Recent days', prepare: 'Prepare proposal', preview: 'Review proposal', save_this: 'Save this case', request_details: 'View request and assertions', confirm: 'I reviewed and confirm the proposed save or execution', apply: 'Confirm action', done: 'Completed', open_result: 'View result', confirm_run: 'Run the new regression suite (may create business data)', run_suite: 'Run regression suite', download: 'Download Markdown',
  partial_load: 'Some project data could not be loaded. Reopen the panel; missing data is excluded.', failed: 'Action failed', editor_required: 'Project editor access is required', choose_case: 'Choose a case in this project', no_recording: 'No low-code steps are available', invalid_steps: 'Recording steps are incomplete', locators_required: 'Enter the original and verified replacement locators', locator_not_found: 'Original locator was not found', locators_changed: 'Replace the locator in {count} steps', expected_required: 'Enter the expected result text; business assertions are not guessed', assertion: 'Verify expected text', timeout_note: 'Use the existing low-code executor preserving the existing timeout (30 seconds when absent), with automatic element waits. Edit the timeout in the preview.', schema_required: 'Choose a module and provide an API description', endpoint_limit: 'Provide 1–20 endpoints', no_drafts: 'The model returned no usable drafts', select_cases: 'Enter a name and select at least one case', not_ready: 'Some selected cases are not ready for execution', run_separate: 'Create a sequential suite first; execution requires separate confirmation. No environment is selected automatically.', device_not_ready: 'The case is not executable or its device is unavailable', apk_missing: 'The configured APK is not in this project', device_cached: 'Readiness uses the last synced device state. ADB, installation, and launch are checked during execution.', installed_app: 'Use the configured installed app', choose_run: 'Choose a failed case run in this project', not_failure: 'The run is no longer failed or errored', evidence_link: 'Link the defect to the original run and check for duplicates.', content_required: 'Enter a title and content', knowledge_draft: 'Save as a project knowledge draft for later editing and publication.', summary_limit: 'Summarizes case runs and open defects. Details include up to 50 runs; aggregates cover the chosen period.', period: 'Period: last {days} days (rolling window)', summary_metrics: '{runs} runs: {passed} passed, {failed} failed, {error} errors; pass rate {rate}%; {defects} currently open defects.', stale: 'The case changed after preview. Prepare a new proposal.', import_failed: 'Import was incomplete. Check the case list before proceeding.', duplicate_defect: 'An existing defect was returned', check_before_retry: 'The request may already have completed. Check records before retrying.', completed_message: '{action} completed. Open the result to review.', run_started: 'Regression run #{id} was submitted. See suite run history.', regression_name: 'Hermes regression suite', knowledge_name: 'Project testing experience',
}
